/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2012-01-04 18:10:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import java.io.*;

public final class composemail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String sendmessage=(String)request.getAttribute("sendmessage");
	if(sendmessage==null)
	{
		sendmessage="";
	}

    if (session == null) {
        response.sendError(404, "Session expired");
        return;
    }
	userinfo info = (userinfo)session.getAttribute("userinfo");
	Folder folder=info.getFolder();
	int count = folder.getMessageCount();
	int unread = folder.getUnreadMessageCount();


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html><head>\r\n");
      out.write("<title>Home Page</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"styleforcomposemail.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("<center>\r\n");
      out.write("<form action='sendmail' method='post' enctype='multipart/form-data'>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t   <tr bgcolor='#800517'>\r\n");
      out.write("\t\t<td colspan='2'><b><h3><center>Compose Your Mail Here</center></h3></b></td>\r\n");
      out.write("\t   </tr>\r\n");
      out.write("\t   <tr height=\"15\" bgcolor='#CFECEC'>\r\n");
      out.write("\t\t<td><b>From :</td>\r\n");
      out.write("\t\t<td><label for=\"login\">");
      out.print( info.getsendfrom() );
      out.write("</label></td>\r\n");
      out.write("\t   </tr>\r\n");
      out.write("\t   <tr height=\"15\" bgcolor='#CFECEC'>\r\n");
      out.write("\t\t<td><b>TO :</td>\r\n");
      out.write("\t\t<td><input type='text' name='sendto' /></b>separate addresses with commas</td>\r\n");
      out.write("\t   </tr>\r\n");
      out.write("\t   <tr height=\"15\" bgcolor='#CFECEC'>\r\n");
      out.write("\t\t<td><b>Subject :</td>\r\n");
      out.write("\t\t<td><input type='text' name='subject'  /></td>\r\n");
      out.write("\t   </tr>\r\n");
      out.write("\t   <tr height=\"15\" bgcolor='#CFECEC'>\r\n");
      out.write("\t\t<td><b \t>Attachment :</td>\r\n");
      out.write("\t\t<td><input type='file' name='attachment' /></b></td>\r\n");
      out.write("\t   </tr>\r\n");
      out.write("\t   <tr bgcolor='#CFECEC'>\r\n");
      out.write("\t\t<td colspan='2'><TEXTAREA rows='35' cols='125' name='data'></TEXTAREA></td>\r\n");
      out.write("\t   </tr>\r\n");
      out.write("\t   <tr height=\"15\" bgcolor='#CFECEC'>\r\n");
      out.write("\t\t<td colspan='2'><input type='submit' class='button' name='Submit' value='Submit'/>\r\n");
      out.write("\t\t\t\t<input type='submit' class='button' name='Draft' value='Draft'/>\r\n");
      out.write("\t\t\t\t<input type='reset' class='button' value='Reset' name='Reset'/>\r\n");
      out.write("\t\t\t\t<input type='reset' class='button' value='Discard' Onclick=\"javascript:discardmail()\" name='Reset'/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t   </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("  </center>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
