/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2012-01-04 18:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import java.io.*;
import javax.mail.Message.*;
import javax.mail.MessagingException.*;

public final class inbox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int MailIndex=Integer.parseInt(request.getParameter("MailIndex"));	
	String sendmessage=(String)request.getAttribute("sendmessage");
	if(sendmessage==null)
	{
		sendmessage="";
	}

    if (session == null) {
        response.sendError(404, "Session expired");
        return;
    }
    userinfo info = (userinfo)session.getAttribute("userinfo");

	Session sessio = info.getSession();
	Store store = sessio.getStore("imap");
        store.connect(info.getHostname(),info.getusername(),info.getpassword());
	Folder folder = store.getFolder(info.getUrl());	
	folder.open(Folder.READ_WRITE);
	Message message = null;
	Message[] messages = folder.getMessages();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html><head><title>Home Page</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<div id=\"displaymail\">\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td valign=\"top\"></td>\r\n");
      out.write("\t<td valign=\"top\"><input type='button' onclick=\"checkUncheck('myForm', true);\" class='button2' value='Check All'/><input type='button' class='button2' onclick=\"checkUncheck('myForm', false);\" value='Uncheck All'/><input type=\"button\" class=\"button2\" name=\"delete\" onclick=\"javascript:deleteselectedmessages()\" value=\"Delete\"/></td>\r\n");
      out.write("\t<td valign=\"top\"></td>\r\n");
      out.write("\t<td valign=\"top\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<td></td>\r\n");
      out.write("\t<td>From</td>\r\n");
      out.write("\t<td>Subject</td>\r\n");
      out.write("\t<td>Date</td>\r\n");
      out.write("\t\r\n");
      out.write(" </tr>\r\n");
      out.write("\r\n");
 for(int i=messages.length-1;i>0;i--){
message=messages[i];
if ((!(message.isSet(Flags.Flag.DRAFT))) && (!(message.isSet(Flags.Flag.DELETED))) && (!(message.isSet(Flags.Flag.FLAGGED))) && (!(message.isSet(Flags.Flag.ANSWERED))))
{
if(message.isSet(Flags.Flag.SEEN))
{

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td  bgcolor=\"#CFECEC\"><input type=\"checkbox\" name=\"mail\" value=\"");
      out.print(i);
      out.write("\" /></td>\r\n");
      out.write("\t<td  bgcolor=\"#CFECEC\"><button name=\"Display1\" style=\"background-color:transparent;border:0px\" class=\"displayemailnormal\" Onclick=\"javascript:loaddisplaymessage(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print( (InternetAddress.toString(message.getFrom())) );
      out.write("<br/>Message No : ");
      out.print(message.getMessageNumber());
      out.write("</button></td>\r\n");
      out.write("\t<td  bgcolor=\"#CFECEC\"><button name=\"Display2\" style=\"background-color:transparent;border:0px\" class=\"displayemailnormal\" Onclick=\"javascript:loaddisplaymessage(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print( message.getSubject() );
      out.write("</button>");
      out.print(i);
      out.write("</td>\r\n");
      out.write("\t<td  bgcolor=\"#CFECEC\"><button name=\"Display3\" style=\"background-color:transparent;border:0px\" class=\"displayemailnormal\" Onclick=\"javascript:loaddisplaymessage(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print( message.getSentDate() );
      out.write("</button></td>\r\n");
      out.write("</tr>\r\n");

}
else
{

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td bgcolor=\"#C8BBBE\"><input type=\"checkbox\" name=\"mail\" value=\"");
      out.print(i);
      out.write("\" /></td>\r\n");
      out.write("\t<td bgcolor=\"#C8BBBE\"><button name=\"Display1\" style=\"background-color:transparent;border:0px\" class=\"displayemailbold\" Onclick=\"javascript:loaddisplaymessage(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print( (InternetAddress.toString(message.getFrom())) );
      out.write("<br/>Message No : ");
      out.print(message.getMessageNumber());
      out.write("</button></td>\r\n");
      out.write("\t<td bgcolor=\"#C8BBBE\"><button name=\"Display2\" style=\"background-color:transparent;border:0px\" class=\"displayemailbold\" Onclick=\"javascript:loaddisplaymessage(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print( message.getSubject() );
      out.write("</button>");
      out.print(i);
      out.write("</td>\r\n");
      out.write("\t<td bgcolor=\"#C8BBBE\"><button name=\"Display3\" style=\"background-color:transparent;border:0px\" class=\"displayemailbold\" Onclick=\"javascript:loaddisplaymessage(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print( message.getSentDate() );
      out.write("</button></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

}

} } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
