/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.23
 * Generated at: 2012-01-04 16:12:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import java.io.*;

public final class DisplaySentMessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String sendmessage=(String)request.getAttribute("sendmessage");
	if(sendmessage==null)
	{
		sendmessage="";
	}

    if (session == null) {
        response.sendError(404, "Session expired");
        return;
    }
	userinfo info = (userinfo)session.getAttribute("userinfo");
	Session sessio = info.getSession();
	Store store = sessio.getStore("imap");
               store.connect(info.getHostname(),info.getusername(),info.getpassword());
	Folder folder = store.getFolder("Sent");	
	folder.open(Folder.READ_WRITE);
	Message[] message = folder.getMessages();
	int count = folder.getMessageCount();
	int unread = folder.getUnreadMessageCount();
	Integer messageno=Integer.parseInt(request.getParameter("messageno"));	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html><head><title>Home Page</title></head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("<table width=\"940\" bgcolor=\"#GSDFES\">\r\n");
      out.write("<tr><td><input type=\"submit\" name=\"button\" class=\"button\" onclick=\"javascript:deletesentmail(");
      out.print(messageno);
      out.write(")\" value=\"Delete Forever\"/></td>\r\n");
      out.write("<tr><td>From : ");
      out.print( message[messageno].getFrom()[0]  );
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Subject : ");
      out.print( message[messageno].getSubject() );
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Date : ");
      out.print( message[messageno].getSentDate() );
      out.write("</td></tr>\r\n");
      out.write("<tr><td>\r\n");

Multipart multipart=(Multipart)message[messageno].getContent();

for(int i=0;i<multipart.getCount();i++)
{
	BodyPart bodypart = multipart.getBodyPart(i);
	String disposition = bodypart.getDisposition();
	if(disposition != null && (disposition.equals(BodyPart.ATTACHMENT)))
	{
	String filename=bodypart.getFileName();
	FileWriter outputFileWriter=new FileWriter("C:\\nikki\\apache-tomcat-7.0.23-windows-x86\\apache-tomcat-7.0.23\\webapps\\Email\\download\\"+filename);
	InputStream inputStream=bodypart.getInputStream();
	int ii;
	while((ii=inputStream.read())!=-1)
	{
		outputFileWriter.write(ii);
	}
	outputFileWriter.close();
	String FilePath="/Email/download/"+filename;	
	
      out.write("<br/><br/><br/><a href=\"");
      out.print(FilePath);
      out.write('"');
      out.write('>');
      out.print(filename);
      out.write("</a>\r\n");
      out.write("\t");

	}else{
	InputStream stream = bodypart.getInputStream();
  	while (stream.available() != 0) {
	char str=((char)stream.read());
	if(str=='\n')
	{	
      out.write("<br/>");
 continue;} 
      out.write('\r');
      out.write('\n');
	if(str==' ')
	{	
      out.write("&nbsp;");
 } 
      out.write('\r');
      out.write('\n');
      out.print( str );
      out.write('\r');
      out.write('\n');

}//while over
}//else over
}//for over

      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("<button class=\"button\" onClick=\"javascript:loadforwardmessage(");
      out.print(messageno);
      out.write(")\" name=\"forward\">Forward</button>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
